<a href="https://colab.research.google.com/github/hwankang/chemometrics-tutorials/blob/master/05(mon)_Dec__10_14_pm_R2_0_445(stacking)_Adaboost_negative_Gradient_Boost_negative_NIR_a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
filename='/content/drive/MyDrive/machine_learning/123_Raman_DATA_csv.csv'
filename_a='/content/drive/MyDrive/machine_learning/A_NIR_DATA_csv.csv'
import pandas as pd
data_a = pd.read_csv(filename_a,header=0, 
                   encoding="unicode-escape")

In [ ]:
xx,yy=data_a.shape
xx

2039

In [ ]:
data_a2=data_a.iloc[0::,1:yy+1]
data_a2.head()

¸ðµ¨ Æ÷ÇÔ   Y_A  899.9280058  900.2520706  900.5763689  900.9009009  \
0       True  24.0     0.098681     0.100515     0.102056     0.100267   
1       True  24.0     0.098081     0.099926     0.101394     0.099664   
2       True  24.0     0.089885     0.092072     0.094055     0.092618   
3       True  23.6     0.088701     0.090287     0.091825     0.090534   
4       True  23.6     0.095273     0.096945     0.098684     0.097460   

   901.2256669  901.5506671  901.8759019  902.2013713  ...  2477.700694  \
0     0.096954     0.096161     0.097151     0.096790  ...     2.968741   
1     0.096598     0.095915     0.096567     0.095609  ...     2.960005   
2     0.089560     0.088900     0.089790     0.089088  ...     2.943931   
3     0.087883     0.087348     0.088151     0.087593  ...     2.935452   
4     0.094674     0.093949     0.094563     0.093743  ...     2.966199   

   2480.15873  2482.621648  2485.089463  2487.562189  2490.039841  \
0    2.968988     2.958685     2.950201     2.950122     2.948725   
1    2.959948     2.951504     2.945633     2.947553     2.947326   
2    2.943679     2.930295     2.919846     2.920668     2.922776   
3    2.938259     2.928736     2.921757     2.924166     2.924666   
4    2.968021     2.955198     2.942411     2.943006     2.942151   

   2492.522433  2495.00998  2497.502498      2500  
0     2.939113    2.929406     2.929555  2.927579  
1     2.937901    2.926926     2.924102  2.920722  
2     2.913596    2.904503     2.903535  2.901086  
3     2.914831    2.905151     2.902643  2.897351  
4     2.931640    2.918549     2.918717  2.917849  

[5 rows x 1781 columns]

In [ ]:
data_a2.iloc[4,0]

True

In [ ]:
ai=[]
for i in range(xx):
    if data_a2.iloc[i,0]==False:
        ai.append(i)
data_a3=data_a2.drop(ai,axis=0) #
data_a3
len(ai)
data_a3

¸ðµ¨ Æ÷ÇÔ    Y_A  899.9280058  900.2520706  900.5763689  900.9009009  \
0          True  24.00     0.098681     0.100515     0.102056     0.100267   
1          True  24.00     0.098081     0.099926     0.101394     0.099664   
2          True  24.00     0.089885     0.092072     0.094055     0.092618   
3          True  23.60     0.088701     0.090287     0.091825     0.090534   
4          True  23.60     0.095273     0.096945     0.098684     0.097460   
...         ...    ...          ...          ...          ...          ...   
2034       True  25.52     0.076506     0.075591     0.074629     0.072980   
2035       True  25.52     0.071916     0.071201     0.070450     0.068871   
2036       True  25.37     0.055557     0.054680     0.053789     0.052091   
2037       True  25.37     0.050590     0.049846     0.049057     0.047327   
2038       True  25.37     0.063837     0.062890     0.062142     0.060671   

      901.2256669  901.5506671  901.8759019  902.2013713  ...  2477.700694  \
0        0.096954     0.096161     0.097151     0.096790  ...     2.968741   
1        0.096598     0.095915     0.096567     0.095609  ...     2.960005   
2        0.089560     0.088900     0.089790     0.089088  ...     2.943931   
3        0.087883     0.087348     0.088151     0.087593  ...     2.935452   
4        0.094674     0.093949     0.094563     0.093743  ...     2.966199   
...           ...          ...          ...          ...  ...          ...   
2034     0.072275     0.072979     0.072688     0.070171  ...     2.962918   
2035     0.068104     0.068746     0.068455     0.065891  ...     2.982798   
2036     0.051338     0.052176     0.052068     0.049510  ...     2.960384   
2037     0.046489     0.047292     0.047258     0.044905  ...     2.968252   
2038     0.060073     0.060987     0.060884     0.058203  ...     2.981493   

      2480.15873  2482.621648  2485.089463  2487.562189  2490.039841  \
0       2.968988     2.958685     2.950201     2.950122     2.948725   
1       2.959948     2.951504     2.945633     2.947553     2.947326   
2       2.943679     2.930295     2.919846     2.920668     2.922776   
3       2.938259     2.928736     2.921757     2.924166     2.924666   
4       2.968021     2.955198     2.942411     2.943006     2.942151   
...          ...          ...          ...          ...          ...   
2034    2.970997     2.967865     2.957785     2.952054     2.949278   
2035    2.982529     2.968697     2.958179     2.962882     2.967330   
2036    2.958313     2.946722     2.938467     2.936874     2.936340   
2037    2.967836     2.953877     2.942397     2.945923     2.948910   
2038    2.981399     2.970350     2.962294     2.963960     2.962348   

      2492.522433  2495.00998  2497.502498      2500  
0        2.939113    2.929406     2.929555  2.927579  
1        2.937901    2.926926     2.924102  2.920722  
2        2.913596    2.904503     2.903535  2.901086  
3        2.914831    2.905151     2.902643  2.897351  
4        2.931640    2.918549     2.918717  2.917849  
...           ...         ...          ...       ...  
2034     2.941087    2.935639     2.936698  2.938116  
2035     2.958188    2.948901     2.948394  2.943151  
2036     2.925951    2.920350     2.921682  2.917657  
2037     2.940729    2.926084     2.923839  2.919868  
2038     2.953168    2.948091     2.949026  2.943110  

[1823 rows x 1781 columns]

In [ ]:
x1,y1=data_a3.shape
data_a1=data_a3.iloc[0::,2:yy+1]
data_a1

899.9280058  900.2520706  900.5763689  900.9009009  901.2256669  \
0        0.098681     0.100515     0.102056     0.100267     0.096954   
1        0.098081     0.099926     0.101394     0.099664     0.096598   
2        0.089885     0.092072     0.094055     0.092618     0.089560   
3        0.088701     0.090287     0.091825     0.090534     0.087883   
4        0.095273     0.096945     0.098684     0.097460     0.094674   
...           ...          ...          ...          ...          ...   
2034     0.076506     0.075591     0.074629     0.072980     0.072275   
2035     0.071916     0.071201     0.070450     0.068871     0.068104   
2036     0.055557     0.054680     0.053789     0.052091     0.051338   
2037     0.050590     0.049846     0.049057     0.047327     0.046489   
2038     0.063837     0.062890     0.062142     0.060671     0.060073   

      901.5506671  901.8759019  902.2013713  902.5270758  902.8530155  ...  \
0        0.096161     0.097151     0.096790     0.095622     0.095521  ...   
1        0.095915     0.096567     0.095609     0.094073     0.093994  ...   
2        0.088900     0.089790     0.089088     0.087585     0.087353  ...   
3        0.087348     0.088151     0.087593     0.086458     0.086425  ...   
4        0.093949     0.094563     0.093743     0.092318     0.092116  ...   
...           ...          ...          ...          ...          ...  ...   
2034     0.072979     0.072688     0.070171     0.068566     0.069321  ...   
2035     0.068746     0.068455     0.065891     0.064076     0.064532  ...   
2036     0.052176     0.052068     0.049510     0.047720     0.048518  ...   
2037     0.047292     0.047258     0.044905     0.043365     0.044220  ...   
2038     0.060987     0.060884     0.058203     0.056162     0.056647  ...   

      2477.700694  2480.15873  2482.621648  2485.089463  2487.562189  \
0        2.968741    2.968988     2.958685     2.950201     2.950122   
1        2.960005    2.959948     2.951504     2.945633     2.947553   
2        2.943931    2.943679     2.930295     2.919846     2.920668   
3        2.935452    2.938259     2.928736     2.921757     2.924166   
4        2.966199    2.968021     2.955198     2.942411     2.943006   
...           ...         ...          ...          ...          ...   
2034     2.962918    2.970997     2.967865     2.957785     2.952054   
2035     2.982798    2.982529     2.968697     2.958179     2.962882   
2036     2.960384    2.958313     2.946722     2.938467     2.936874   
2037     2.968252    2.967836     2.953877     2.942397     2.945923   
2038     2.981493    2.981399     2.970350     2.962294     2.963960   

      2490.039841  2492.522433  2495.00998  2497.502498      2500  
0        2.948725     2.939113    2.929406     2.929555  2.927579  
1        2.947326     2.937901    2.926926     2.924102  2.920722  
2        2.922776     2.913596    2.904503     2.903535  2.901086  
3        2.924666     2.914831    2.905151     2.902643  2.897351  
4        2.942151     2.931640    2.918549     2.918717  2.917849  
...           ...          ...         ...          ...       ...  
2034     2.949278     2.941087    2.935639     2.936698  2.938116  
2035     2.967330     2.958188    2.948901     2.948394  2.943151  
2036     2.936340     2.925951    2.920350     2.921682  2.917657  
2037     2.948910     2.940729    2.926084     2.923839  2.919868  
2038     2.962348     2.953168    2.948091     2.949026  2.943110  

[1823 rows x 1779 columns]

In [ ]:
#preperation
df=pd.DataFrame({
    'bool':['true','false','true','false'],
    'int':[1,2,3,4]
})
df2=df
df.iloc[0,0]
df

In [ ]:
range(4)

In [ ]:
ai=[]
for i in range(4):
    if df.iloc[i,0]=='false':
        ai.append(i)
df2=df.drop(ai,axis=0) #
df2

In [ ]:
data_a1_n=data_a1.to_numpy()
data_a1_input=data_a1_n
data_a1_input

array([[0.09868074, 0.1005148 , 0.10205633, ..., 2.92940605, 2.9295551 ,
        2.92757921],
       [0.0980814 , 0.09992567, 0.10139396, ..., 2.92692573, 2.92410227,
        2.92072185],
       [0.08988517, 0.09207206, 0.0940546 , ..., 2.90450321, 2.90353459,
        2.90108571],
       ...,
       [0.05555697, 0.05468017, 0.05378911, ..., 2.92035018, 2.92168167,
        2.917657  ],
       [0.05058956, 0.0498458 , 0.04905745, ..., 2.92608398, 2.92383935,
        2.91986778],
       [0.06383698, 0.06289033, 0.06214161, ..., 2.94809062, 2.94902612,
        2.9431105 ]])

In [ ]:
data_a1_output=data_a3.iloc[0::,1:2]
data_a1_output.head()

Y_A
0  24.0
1  24.0
2  24.0
3  23.6
4  23.6

In [ ]:
data_a1_output_n=data_a1_output.to_numpy().flatten()
data_a1_target=data_a1_output_n
data_a1_target

array([24.  , 24.  , 24.  , ..., 25.37, 25.37, 25.37])

In [ ]:
from sklearn.datasets import load_breast_cancer

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, accuracy_score, confusion_matrix, recall_score, precision_score

import seaborn as sns
import matplotlib.pyplot as plt 
import matplotlib.font_manager as fm 

In [ ]:
data_a1_input

array([[0.09868074, 0.1005148 , 0.10205633, ..., 2.92940605, 2.9295551 ,
        2.92757921],
       [0.0980814 , 0.09992567, 0.10139396, ..., 2.92692573, 2.92410227,
        2.92072185],
       [0.08988517, 0.09207206, 0.0940546 , ..., 2.90450321, 2.90353459,
        2.90108571],
       ...,
       [0.05555697, 0.05468017, 0.05378911, ..., 2.92035018, 2.92168167,
        2.917657  ],
       [0.05058956, 0.0498458 , 0.04905745, ..., 2.92608398, 2.92383935,
        2.91986778],
       [0.06383698, 0.06289033, 0.06214161, ..., 2.94809062, 2.94902612,
        2.9431105 ]])

In [ ]:
data_a1_target

array([24.  , 24.  , 24.  , ..., 25.37, 25.37, 25.37])

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.ensemble import BaggingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [ ]:
base_model= make_pipeline(
    StandardScaler(),
    KNeighborsRegressor()
)

#bagging_model=BaggingRegressor(base_model, n_estimators=10, max_samples=0.5, max_features=0.5)
bagging_model=BaggingRegressor(base_model, n_estimators=10, max_samples=1, max_features=1)

In [ ]:
cross_val=cross_validate(
    estimator=base_model,
#    X=boston.data, y=boston.target,
#    X=raman, y=raman_target,
     X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 0.045820188522338864 (+/-0.0015844369345036004)
avg score time: 0.0685882568359375 (+/- 0.0034261888532887974)
avg test score: -1.4419025215900863 (+/- 0.6318436938149143)


In [ ]:
cross_val=cross_validate(
    estimator=bagging_model,
#   X=raman, y=raman_target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 0.02366957664489746 (+/-0.003129542901781206)
avg score time: 0.0010915756225585937 (+/- 0.0007816880935425778)
avg test score: nan (+/- nan)


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_scorer.py", line 418, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 705, in score
    y_pred = self.predict(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_bagging.py", line 1129, in predict
    all_y_hat = Parallel(n_jobs=n_jobs, verbose=self.verbose)(
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages

In [ ]:
base_model= make_pipeline(
    StandardScaler(),
    KNeighborsRegressor()
)

bagging_model=BaggingRegressor(base_model, n_estimators=10, max_samples=1, max_features=1)

In [ ]:
cross_val=cross_validate(
    estimator=bagging_model,
#   X=raman, y=raman_target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 0.02416958808898926 (+/-0.0028658162677650196)
avg score time: 0.000666666030883789 (+/- 5.8494413195786545e-05)
avg test score: nan (+/- nan)


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_scorer.py", line 418, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 705, in score
    y_pred = self.predict(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_bagging.py", line 1129, in predict
    all_y_hat = Parallel(n_jobs=n_jobs, verbose=self.verbose)(
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages

SVR

In [ ]:
base_model= make_pipeline(
    StandardScaler(),
    SVR()
)

In [ ]:
cross_val=cross_validate(
    estimator=base_model,
#   X=raman, y=raman_target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 1.2718009948730469 (+/-0.03652763700187674)
avg score time: 0.5947352409362793 (+/- 0.09062761796551676)
avg test score: -0.9165702147180393 (+/- 0.4658393073533814)


In [ ]:
cross_val=cross_validate(
    estimator=bagging_model,
#   X=raman, y=raman_target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 0.02372879981994629 (+/-0.0029020430670869575)
avg score time: 0.0007717132568359375 (+/- 6.118982060635792e-05)
avg test score: nan (+/- nan)


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_scorer.py", line 418, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 705, in score
    y_pred = self.predict(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_bagging.py", line 1129, in predict
    all_y_hat = Parallel(n_jobs=n_jobs, verbose=self.verbose)(
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages

Decision Tree

In [ ]:
base_model= make_pipeline(
    StandardScaler(),
    DecisionTreeRegressor()
)

bagging_model=BaggingRegressor(base_model, n_estimators=10, max_samples=0.5, max_features=0.5)

In [ ]:
cross_val=cross_validate(
    estimator=base_model,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 2.6703796863555906 (+/-0.920426204008081)
avg score time: 0.005116891860961914 (+/- 0.0003251150227726041)
avg test score: -1.8212000068182632 (+/- 0.5811561372608995)


In [ ]:
cross_val=cross_validate(
    estimator=bagging_model,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 4.572564554214478 (+/-0.5080498456882404)
avg score time: 0.0305997371673584 (+/- 0.00032107859701645855)
avg test score: -1.2071364465231909 (+/- 0.6944107596180656)


Forests of randomized trees

##1)Random Forest
##2) Extra-tree

In [ ]:
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.ensemble import RandomForestRegressor,ExtraTreesRegressor

In [ ]:
model =make_pipeline(
    StandardScaler(),
    RandomForestRegressor()
)

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 126.4928403377533 (+/-9.623167307134485)
avg score time: 0.020734024047851563 (+/- 0.0018296590927983736)
avg test score: -0.9897800387582553 (+/- 0.5343143224253185)


EXtremely Randomized Trees

In [ ]:
model =make_pipeline(
    StandardScaler(),
    ExtraTreesRegressor()
)

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 38.80483794212341 (+/-2.5960222498418943)
avg score time: 0.020905208587646485 (+/- 0.0016642307223451503)
avg test score: -1.100858485618148 (+/- 0.5192900622514408)


Adaboost

In [ ]:
from sklearn.ensemble import AdaBoostRegressor

In [ ]:
model = make_pipeline(
    StandardScaler(),
    AdaBoostRegressor()
)

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=10)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))
cross_val['test_score']

avg fit time: 21.0720064163208 (+/-0.5881480215706448)
avg score time: 0.030605673789978027 (+/- 0.0011593899956921264)
avg test score: -0.7580925581625175 (+/- 0.5224523036543586)


array([-2.14601707, -1.00763221, -0.3468731 , -0.70932487, -0.52510098,
       -0.15535816, -0.68780486, -0.59914464, -0.46165638, -0.94201332])

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

avg fit time: 18.05485577583313 (+/-0.48392065170040377)
avg score time: 0.05358576774597168 (+/- 0.0012743199035938674)
avg test score: -0.9392283789188914 (+/- 0.7698633597497156)


Gradient Tree boosting

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
model = make_pipeline(
    StandardScaler(),
    GradientBoostingRegressor()
)

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=10)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))
cross_val['test_score']

avg fit time: 68.75200200080872 (+/-0.610956789046703)
avg score time: 0.003492307662963867 (+/- 5.532244077452334e-05)
avg test score: -0.6875897940572046 (+/- 0.4174246111352803)


array([-1.4303515 , -0.22563045, -0.59361052, -1.20796337, -0.37889559,
       -0.57134849, -1.14557941, -0.29868318, -0.22366214, -0.80017329])

Regressor vote

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.model_selection import cross_val_score

In [ ]:
model1=LinearRegression()
model2=GradientBoostingRegressor()
model3=RandomForestRegressor()
vote_model =VotingRegressor(estimators=[('linear',model1),('gbr',model2),('rfr',model3)],
                              weights=[1,1,1])

In [ ]:
for model in [model1,model2,model3,vote_model]:
    model_name=str(type(model)).split('.')[-1][:-2]
    scores=cross_val_score(model,data_a1_input,data_a1_target,cv=20)
    print('R2: %0.2f (+/- %0.2f) [%s]' % ( scores.mean(), scores.std(), model_name))

R2: -3086.72 (+/- 13321.88) [LinearRegression]
R2: -1.84 (+/- 2.50) [GradientBoostingRegressor]


KeyboardInterrupt: ignored

스택회귀

In [ ]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import StackingRegressor

In [ ]:
estimators=[('ridge',Ridge()),
            ('lasso',Lasso()),
            ('svr',SVR())]

In [ ]:
reg = make_pipeline(
    StandardScaler(),
    StackingRegressor(
        estimators=estimators,
        final_estimator=GradientBoostingRegressor()
)
)

In [ ]:
cross_val=cross_validate(
    estimator=reg,
    X=data_a1_input, y=data_a1_target,
    cv=10)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/-{})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/-{})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))
cross_val['test_score']

avg fit time: 11.186891531944275 (+/-0.3388646858065281)
avg score time: 0.3847131013870239 (+/-0.0783690524610559)
avg test score: -0.44060417354618087 (+/-1.3513189059998405)


array([-0.23897677,  0.41236719,  0.30956051, -4.22360059, -1.12012059,
        0.44538645,  0.41049559,  0.3485722 , -0.28522689, -0.46449884])