<a href="https://colab.research.google.com/github/hwankang/chemometrics-tutorials/blob/master/11(sun)_12_04_00_pm_stacking_0_952_29(sat)_Nov__7_56_pm_R2_0_952(stacking)_Adaboost_0_196_Gradient_Boost_0_294_NIR_b_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
filename='/content/drive/MyDrive/machine_learning/123_Raman_DATA_csv.csv'
filename_a='/content/drive/MyDrive/machine_learning/B_NIR_DATA_csv.csv'
import pandas as pd
data_a = pd.read_csv(filename_a,header=0, 
                   encoding="unicode-escape")

In [4]:
xx,yy=data_a.shape
xx

624

In [5]:
data_a2=data_a.iloc[0::,1:yy+1]
data_a2.head()

¸ðµ¨ Æ÷ÇÔ  Y_B  899.9280058  900.2520706  900.5763689  900.9009009  \
0       True  2.0     0.276093     0.279368     0.282974     0.283645   
1       True  1.8     0.199544     0.202455     0.206198     0.207755   
2       True  6.7     0.306803     0.309845     0.313508     0.314680   
3       True  6.2     0.286879     0.290392     0.294110     0.294774   
4      False  5.1     0.253218     0.256407     0.260161     0.261418   

   901.2256669  901.5506671  901.8759019  902.2013713  ...  2477.700694  \
0     0.283141     0.282718     0.281553     0.279137  ...     2.949425   
1     0.208028     0.207398     0.205435     0.202679  ...     2.981332   
2     0.314671     0.314172     0.312433     0.309447  ...     2.991938   
3     0.294035     0.293060     0.291292     0.288594  ...     2.991402   
4     0.261547     0.261116     0.259408     0.256675  ...     3.004459   

   2480.15873  2482.621648  2485.089463  2487.562189  2490.039841  \
0    2.949937     2.940435     2.930193     2.927044     2.926591   
1    2.984826     2.975499     2.964666     2.964128     2.967567   
2    2.992541     2.984488     2.976776     2.975918     2.973828   
3    2.990624     2.980183     2.970664     2.967151     2.961850   
4    3.005398     3.000151     2.995331     2.997660     2.999729   

   2492.522433  2495.00998  2497.502498      2500  
0     2.917971    2.911627     2.911584  2.909855  
1     2.960830    2.954538     2.956946  2.955335  
2     2.963011    2.955492     2.954702  2.949301  
3     2.948892    2.939125     2.938542  2.934796  
4     2.992129    2.987290     2.988690  2.987576  

[5 rows x 1781 columns]

In [6]:
data_a2.iloc[4,0]

False

In [7]:
ai=[]
for i in range(xx):
    if data_a2.iloc[i,0]==False:
        ai.append(i)
data_a3=data_a2.drop(ai,axis=0) #
data_a3
len(ai)
data_a3

¸ðµ¨ Æ÷ÇÔ   Y_B  899.9280058  900.2520706  900.5763689  900.9009009  \
0         True   2.0     0.276093     0.279368     0.282974     0.283645   
1         True   1.8     0.199544     0.202455     0.206198     0.207755   
2         True   6.7     0.306803     0.309845     0.313508     0.314680   
3         True   6.2     0.286879     0.290392     0.294110     0.294774   
12        True   2.2     0.137633     0.141045     0.144793     0.145757   
..         ...   ...          ...          ...          ...          ...   
619       True   8.6     0.231522     0.230534     0.231280     0.231104   
620       True  10.8     0.227531     0.226628     0.227406     0.227385   
621       True  12.2     0.224536     0.223379     0.224203     0.224431   
622       True  13.4     0.226519     0.225667     0.226440     0.226193   
623       True  15.8     0.233873     0.232724     0.233435     0.233191   

     901.2256669  901.5506671  901.8759019  902.2013713  ...  2477.700694  \
0       0.283141     0.282718     0.281553     0.279137  ...     2.949425   
1       0.208028     0.207398     0.205435     0.202679  ...     2.981332   
2       0.314671     0.314172     0.312433     0.309447  ...     2.991938   
3       0.294035     0.293060     0.291292     0.288594  ...     2.991402   
12      0.145570     0.145180     0.143793     0.141257  ...     2.912618   
..           ...          ...          ...          ...  ...          ...   
619     0.230198     0.229698     0.229015     0.227028  ...     2.925508   
620     0.226585     0.225993     0.225327     0.223806  ...     2.945441   
621     0.223999     0.223736     0.222991     0.220813  ...     2.966221   
622     0.225218     0.224726     0.224143     0.222250  ...     2.936783   
623     0.232077     0.231309     0.230551     0.228832  ...     2.936938   

     2480.15873  2482.621648  2485.089463  2487.562189  2490.039841  \
0      2.949937     2.940435     2.930193     2.927044     2.926591   
1      2.984826     2.975499     2.964666     2.964128     2.967567   
2      2.992541     2.984488     2.976776     2.975918     2.973828   
3      2.990624     2.980183     2.970664     2.967151     2.961850   
12     2.911201     2.898590     2.887394     2.886869     2.887019   
..          ...          ...          ...          ...          ...   
619    2.927053     2.920447     2.915572     2.920224     2.922330   
620    2.943505     2.933849     2.929372     2.934153     2.933573   
621    2.969063     2.961253     2.952713     2.949854     2.944465   
622    2.939133     2.927408     2.915374     2.913538     2.912847   
623    2.938734     2.926707     2.915750     2.916544     2.919218   

     2492.522433  2495.00998  2497.502498      2500  
0       2.917971    2.911627     2.911584  2.909855  
1       2.960830    2.954538     2.956946  2.955335  
2       2.963011    2.955492     2.954702  2.949301  
3       2.948892    2.939125     2.938542  2.934796  
12      2.875892    2.863482     2.862177  2.858754  
..           ...         ...          ...       ...  
619     2.909775    2.897480     2.897737  2.897391  
620     2.921115    2.910637     2.914499  2.916288  
621     2.929207    2.920399     2.922437  2.923226  
622     2.901005    2.891991     2.894289  2.893951  
623     2.910248    2.899414     2.894074  2.890147  

[313 rows x 1781 columns]

In [8]:
x1,y1=data_a3.shape
data_a1=data_a3.iloc[0::,2:yy+1]
data_a1

899.9280058  900.2520706  900.5763689  900.9009009  901.2256669  \
0       0.276093     0.279368     0.282974     0.283645     0.283141   
1       0.199544     0.202455     0.206198     0.207755     0.208028   
2       0.306803     0.309845     0.313508     0.314680     0.314671   
3       0.286879     0.290392     0.294110     0.294774     0.294035   
12      0.137633     0.141045     0.144793     0.145757     0.145570   
..           ...          ...          ...          ...          ...   
619     0.231522     0.230534     0.231280     0.231104     0.230198   
620     0.227531     0.226628     0.227406     0.227385     0.226585   
621     0.224536     0.223379     0.224203     0.224431     0.223999   
622     0.226519     0.225667     0.226440     0.226193     0.225218   
623     0.233873     0.232724     0.233435     0.233191     0.232077   

     901.5506671  901.8759019  902.2013713  902.5270758  902.8530155  ...  \
0       0.282718     0.281553     0.279137     0.279341     0.282978  ...   
1       0.207398     0.205435     0.202679     0.203198     0.207066  ...   
2       0.314172     0.312433     0.309447     0.309265     0.312464  ...   
3       0.293060     0.291292     0.288594     0.288835     0.292392  ...   
12      0.145180     0.143793     0.141257     0.141577     0.145204  ...   
..           ...          ...          ...          ...          ...  ...   
619     0.229698     0.229015     0.227028     0.224940     0.224793  ...   
620     0.225993     0.225327     0.223806     0.222423     0.222653  ...   
621     0.223736     0.222991     0.220813     0.218589     0.218392  ...   
622     0.224726     0.224143     0.222250     0.220084     0.219543  ...   
623     0.231309     0.230551     0.228832     0.227284     0.227713  ...   

     2477.700694  2480.15873  2482.621648  2485.089463  2487.562189  \
0       2.949425    2.949937     2.940435     2.930193     2.927044   
1       2.981332    2.984826     2.975499     2.964666     2.964128   
2       2.991938    2.992541     2.984488     2.976776     2.975918   
3       2.991402    2.990624     2.980183     2.970664     2.967151   
12      2.912618    2.911201     2.898590     2.887394     2.886869   
..           ...         ...          ...          ...          ...   
619     2.925508    2.927053     2.920447     2.915572     2.920224   
620     2.945441    2.943505     2.933849     2.929372     2.934153   
621     2.966221    2.969063     2.961253     2.952713     2.949854   
622     2.936783    2.939133     2.927408     2.915374     2.913538   
623     2.936938    2.938734     2.926707     2.915750     2.916544   

     2490.039841  2492.522433  2495.00998  2497.502498      2500  
0       2.926591     2.917971    2.911627     2.911584  2.909855  
1       2.967567     2.960830    2.954538     2.956946  2.955335  
2       2.973828     2.963011    2.955492     2.954702  2.949301  
3       2.961850     2.948892    2.939125     2.938542  2.934796  
12      2.887019     2.875892    2.863482     2.862177  2.858754  
..           ...          ...         ...          ...       ...  
619     2.922330     2.909775    2.897480     2.897737  2.897391  
620     2.933573     2.921115    2.910637     2.914499  2.916288  
621     2.944465     2.929207    2.920399     2.922437  2.923226  
622     2.912847     2.901005    2.891991     2.894289  2.893951  
623     2.919218     2.910248    2.899414     2.894074  2.890147  

[313 rows x 1779 columns]

In [9]:
data_a1_n=data_a1.to_numpy()
data_a1_input=data_a1_n
data_a1_input

array([[0.27609259, 0.27936762, 0.28297358, ..., 2.91162677, 2.91158401,
        2.90985458],
       [0.19954403, 0.20245471, 0.20619798, ..., 2.95453844, 2.95694632,
        2.95533475],
       [0.3068027 , 0.3098446 , 0.31350789, ..., 2.95549201, 2.9547023 ,
        2.94930113],
       ...,
       [0.22453563, 0.22337879, 0.22420344, ..., 2.92039857, 2.92243662,
        2.92322634],
       [0.22651915, 0.22566712, 0.22644003, ..., 2.89199138, 2.89428919,
        2.8939513 ],
       [0.23387301, 0.23272414, 0.23343534, ..., 2.89941353, 2.89407375,
        2.89014733]])

In [10]:
data_a1_output=data_a3.iloc[0::,1:2]
data_a1_output.head()

Y_B
0   2.0
1   1.8
2   6.7
3   6.2
12  2.2

In [11]:
data_a1_output_n=data_a1_output.to_numpy().flatten()
data_a1_target=data_a1_output_n
data_a1_target

array([ 2.   ,  1.8  ,  6.7  ,  6.2  ,  2.2  ,  2.4  ,  4.   ,  7.8  ,
        9.4  ,  8.2  ,  3.7  ,  3.6  ,  5.7  ,  7.8  ,  6.4  , 11.9  ,
        3.7  ,  6.   ,  7.9  ,  6.5  , 12.2  ,  3.8  ,  3.1  ,  3.7  ,
        8.2  ,  9.8  ,  3.9  ,  3.7  ,  6.1  ,  8.5  ,  9.7  , 12.6  ,
        3.5  ,  3.7  ,  5.5  ,  7.7  ,  9.4  , 10.9  ,  0.6  ,  2.   ,
        3.3  ,  5.4  ,  9.7  ,  2.2  ,  2.4  ,  4.   ,  7.8  ,  9.4  ,
        8.2  ,  3.7  ,  3.6  ,  5.7  ,  7.8  ,  6.4  ,  3.7  ,  1.8  ,
        6.   ,  7.9  ,  6.5  , 12.2  ,  3.8  ,  3.1  ,  3.7  ,  8.2  ,
        9.8  ,  3.9  ,  3.7  ,  6.1  ,  8.5  ,  9.7  , 12.6  ,  3.5  ,
        3.7  ,  5.5  ,  7.7  ,  9.4  , 10.9  ,  0.6  ,  2.   ,  3.3  ,
        5.4  ,  9.7  ,  3.256,  3.185,  5.303,  7.076,  7.907, 10.775,
        2.921,  3.19 ,  5.359,  7.221,  8.563, 10.755,  3.102,  2.792,
        5.231,  7.233,  8.376, 10.826,  3.154,  2.9  ,  5.334,  7.223,
        8.483, 10.932,  3.128,  3.234,  5.305,  7.323,  8.33 , 10.531,
      

In [12]:
from sklearn.datasets import load_breast_cancer

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, accuracy_score, confusion_matrix, recall_score, precision_score

import seaborn as sns
import matplotlib.pyplot as plt 
import matplotlib.font_manager as fm 

In [13]:
data_a1_input

array([[0.27609259, 0.27936762, 0.28297358, ..., 2.91162677, 2.91158401,
        2.90985458],
       [0.19954403, 0.20245471, 0.20619798, ..., 2.95453844, 2.95694632,
        2.95533475],
       [0.3068027 , 0.3098446 , 0.31350789, ..., 2.95549201, 2.9547023 ,
        2.94930113],
       ...,
       [0.22453563, 0.22337879, 0.22420344, ..., 2.92039857, 2.92243662,
        2.92322634],
       [0.22651915, 0.22566712, 0.22644003, ..., 2.89199138, 2.89428919,
        2.8939513 ],
       [0.23387301, 0.23272414, 0.23343534, ..., 2.89941353, 2.89407375,
        2.89014733]])

In [14]:
data_a1_target

array([ 2.   ,  1.8  ,  6.7  ,  6.2  ,  2.2  ,  2.4  ,  4.   ,  7.8  ,
        9.4  ,  8.2  ,  3.7  ,  3.6  ,  5.7  ,  7.8  ,  6.4  , 11.9  ,
        3.7  ,  6.   ,  7.9  ,  6.5  , 12.2  ,  3.8  ,  3.1  ,  3.7  ,
        8.2  ,  9.8  ,  3.9  ,  3.7  ,  6.1  ,  8.5  ,  9.7  , 12.6  ,
        3.5  ,  3.7  ,  5.5  ,  7.7  ,  9.4  , 10.9  ,  0.6  ,  2.   ,
        3.3  ,  5.4  ,  9.7  ,  2.2  ,  2.4  ,  4.   ,  7.8  ,  9.4  ,
        8.2  ,  3.7  ,  3.6  ,  5.7  ,  7.8  ,  6.4  ,  3.7  ,  1.8  ,
        6.   ,  7.9  ,  6.5  , 12.2  ,  3.8  ,  3.1  ,  3.7  ,  8.2  ,
        9.8  ,  3.9  ,  3.7  ,  6.1  ,  8.5  ,  9.7  , 12.6  ,  3.5  ,
        3.7  ,  5.5  ,  7.7  ,  9.4  , 10.9  ,  0.6  ,  2.   ,  3.3  ,
        5.4  ,  9.7  ,  3.256,  3.185,  5.303,  7.076,  7.907, 10.775,
        2.921,  3.19 ,  5.359,  7.221,  8.563, 10.755,  3.102,  2.792,
        5.231,  7.233,  8.376, 10.826,  3.154,  2.9  ,  5.334,  7.223,
        8.483, 10.932,  3.128,  3.234,  5.305,  7.323,  8.33 , 10.531,
      

In [15]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler

In [16]:
from sklearn.ensemble import BaggingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

In [17]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [19]:
base_model= make_pipeline(
    StandardScaler(),
    KNeighborsRegressor()
)

#bagging_model=BaggingRegressor(base_model, n_estimators=10, max_samples=0.5, max_features=0.5)
bagging_model=BaggingRegressor(base_model, n_estimators=10, max_samples=1, max_features=1)

In [ ]:
cross_val=cross_validate(
    estimator=base_model,
#    X=boston.data, y=boston.target,
#    X=raman, y=raman_target,
     X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

In [ ]:
cross_val=cross_validate(
    estimator=bagging_model,
#   X=raman, y=raman_target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

In [ ]:
base_model= make_pipeline(
    StandardScaler(),
    KNeighborsRegressor()
)

bagging_model=BaggingRegressor(base_model, n_estimators=10, max_samples=1, max_features=1)

In [ ]:
cross_val=cross_validate(
    estimator=bagging_model,
#   X=raman, y=raman_target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

SVR

In [ ]:
base_model= make_pipeline(
    StandardScaler(),
    SVR()
)

In [ ]:
cross_val=cross_validate(
    estimator=base_model,
#   X=raman, y=raman_target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

In [ ]:
cross_val=cross_validate(
    estimator=bagging_model,
#   X=raman, y=raman_target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

Decision Tree

In [ ]:
base_model= make_pipeline(
    StandardScaler(),
    DecisionTreeRegressor()
)

bagging_model=BaggingRegressor(base_model, n_estimators=10, max_samples=0.5, max_features=0.5)

In [ ]:
cross_val=cross_validate(
    estimator=base_model,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

In [ ]:
cross_val=cross_validate(
    estimator=bagging_model,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

Forests of randomized trees

##1)Random Forest
##2) Extra-tree

In [20]:
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.ensemble import RandomForestRegressor,ExtraTreesRegressor

In [21]:
model =make_pipeline(
    StandardScaler(),
    RandomForestRegressor()
)

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

EXtremely Randomized Trees

In [22]:
model =make_pipeline(
    StandardScaler(),
    ExtraTreesRegressor()
)

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

Adaboost

In [23]:
from sklearn.ensemble import AdaBoostRegressor

In [24]:
model = make_pipeline(
    StandardScaler(),
    AdaBoostRegressor()
)

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=10)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))
cross_val['test_score']

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=5)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))

Gradient Tree boosting

In [25]:
from sklearn.ensemble import GradientBoostingRegressor

In [26]:
model = make_pipeline(
    StandardScaler(),
    GradientBoostingRegressor()
)

In [ ]:
cross_val=cross_validate(
    estimator=model,
    #X=boston.data, y=boston.target,
    X=data_a1_input, y=data_a1_target,
    cv=10)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/- {})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/- {})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))
cross_val['test_score']

Regressor vote

In [27]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.model_selection import cross_val_score

In [28]:
model1=LinearRegression()
model2=GradientBoostingRegressor()
model3=RandomForestRegressor()
vote_model =VotingRegressor(estimators=[('linear',model1),('gbr',model2),('rfr',model3)],
                              weights=[1,1,1])

In [ ]:
for model in [model1,model2,model3,vote_model]:
    model_name=str(type(model)).split('.')[-1][:-2]
    scores=cross_val_score(model,data_a1_input,data_a1_target,cv=20)
    print('R2: %0.2f (+/- %0.2f) [%s]' % ( scores.mean(), scores.std(), model_name))

스택회귀

In [29]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import StackingRegressor

In [30]:
estimators=[('ridge',Ridge()),
            ('lasso',Lasso()),
            ('svr',SVR())]

In [31]:
reg = make_pipeline(
    StandardScaler(),
    StackingRegressor(
        estimators=estimators,
        final_estimator=GradientBoostingRegressor()
)
)

In [32]:
cross_val=cross_validate(
    estimator=reg,
    X=data_a1_input, y=data_a1_target,
    cv=10)
print('avg fit time: {} (+/-{})'.format(cross_val['fit_time'].mean(), cross_val['fit_time'].std()))
print('avg score time: {} (+/-{})'.format(cross_val['score_time'].mean(), cross_val['score_time'].std()))
print('avg test score: {} (+/-{})'.format(cross_val['test_score'].mean(), cross_val['test_score'].std()))
cross_val['test_score']

avg fit time: 1.1271006107330321 (+/-0.12507418371749296)
avg score time: 0.020705223083496094 (+/-0.001175355794217074)
avg test score: 0.8159259982299302 (+/-0.10861394014758106)


array([0.69247363, 0.74673477, 0.8629787 , 0.95236475, 0.88950746,
       0.90080231, 0.85469437, 0.82935544, 0.86096368, 0.56938487])